<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNnDRnSx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNnDRnSx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNnDRnSx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNnDRnSx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNnDRnSx\App_KernelDevDebugContainer([
    'container.build_hash' => 'NnDRnSx',
    'container.build_id' => '011481b3',
    'container.build_time' => 1676319447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNnDRnSx');
