<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqOlt2u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqOlt2u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSqOlt2u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSqOlt2u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSqOlt2u\App_KernelDevDebugContainer([
    'container.build_hash' => 'SqOlt2u',
    'container.build_id' => 'bbcd8367',
    'container.build_time' => 1676233019,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqOlt2u');
